package com.ushwamala.javacourse.SpringAnnotations.Apps;

import com.ushwamala.javacourse.SpringAnnotations.Components.TennisCoach;
import org.springframework.context.support.ClassPathXmlApplicationContext;

public class AnnotationsDemoApp {
    public static void main(String[] args) {

        //read spring config file
        ClassPathXmlApplicationContext context =
                new ClassPathXmlApplicationContext("Annotations-applicationContext.xml");

        //retrieve beans from the spring container
        //the beanId is generated by spring if the id is not defined explicitly defined in the @Component("beanId")
        TennisCoach tennisCoach = context.getBean("tennisCoach", TennisCoach.class);
        //TennisCoach newTennisCoach = context.getBean("tennisCoach", TennisCoach.class);
        //BaeldungClass baeld = context.getBean("baeldung",BaeldungClass.class);

        //call methods on the beans
        System.out.println(tennisCoach.getDailyWorkout());
        System.out.println(tennisCoach.getDailyFortune());
        /*System.out.println(tennisCoach.getEmail());
        System.out.println(tennisCoach.getTeam());*/

        //baeld.main();


        //Testing the scope
        /*boolean isSame = (tennisCoach == newTennisCoach);
        if(isSame){
            System.out.println("Scope: Singleton " + tennisCoach);
        } else{
            System.out.println("Scope: Prototype " + tennisCoach.toString() + "\n" + newTennisCoach.toString() );}
*/



        //close context
        context.close();
    }
}
